# AUTOGENERATED FROM 'queries/create_user.edgeql' WITH:
#     $ edgedb-py


from __future__ import annotations
import dataclasses
import edgedb
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class CreateUserResult(NoPydanticValidation):
    id: uuid.UUID


async def create_user(
    executor: edgedb.AsyncIOExecutor,
    *,
    name: str,
    email: str,
    username: str,
    admin: bool,
    subscriber: bool,
    hashed_password: str,
) -> CreateUserResult:
    return await executor.query_single(
        """\
        # createUser.edgeql

        insert User {
          name := <str>$name,
          email := <str>$email,
          username := <str>$username,
          admin := <bool>$admin,
          subscriber := <bool>$subscriber,
          hashed_password := <str>$hashed_password
        }\
        """,
        name=name,
        email=email,
        username=username,
        admin=admin,
        subscriber=subscriber,
        hashed_password=hashed_password,
    )
