# AUTOGENERATED FROM 'queries/create_company.edgeql' WITH:
#     $ edgedb-py


from __future__ import annotations
import dataclasses
import datetime
import edgedb
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class CreateCompanyResult(NoPydanticValidation):
    id: uuid.UUID


async def create_company(
    executor: edgedb.AsyncIOExecutor,
    *,
    name: str,
    founded_date: datetime.date,
    country: str,
    website: str,
    email: str,
    contact_no: str,
) -> CreateCompanyResult:
    return await executor.query_single(
        """\
        # createCompany.edgeql

        insert Company {
          name := <str>$name,
          founded_date := <cal::local_date>$founded_date,
          country := <str>$country,
          website := <str>$website,
          email := <str>$email,
          contact_no := <str>$contact_no
        }\
        """,
        name=name,
        founded_date=founded_date,
        country=country,
        website=website,
        email=email,
        contact_no=contact_no,
    )
