# AUTOGENERATED FROM 'queries/delete_news.edgeql' WITH:
#     $ edgedb-py


from __future__ import annotations
import dataclasses
import edgedb
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class DeleteNewsResult(NoPydanticValidation):
    id: uuid.UUID


async def delete_news(
    executor: edgedb.AsyncIOExecutor,
    *,
    news_id: uuid.UUID,
) -> DeleteNewsResult | None:
    return await executor.query_single(
        """\
        delete News
        filter .id = <uuid>$news_id;\
        """,
        news_id=news_id,
    )
