# AUTOGENERATED FROM 'queries/get_company.edgeql' WITH:
#     $ edgedb-py


from __future__ import annotations
import dataclasses
import datetime
import edgedb
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class GetCompanyResult(NoPydanticValidation):
    id: uuid.UUID
    name: str
    founded_date: datetime.date
    country: str
    website: str
    email: str
    contact_no: str


async def get_company(
    executor: edgedb.AsyncIOExecutor,
) -> list[GetCompanyResult]:
    return await executor.query(
        """\
        select Company {
          name ,
          founded_date ,
          country,
          website,
          email ,
          contact_no 
        }\
        """,
    )
