# AUTOGENERATED FROM 'queries/get_user_by_username.edgeql' WITH:
#     $ edgedb-py


from __future__ import annotations
import dataclasses
import edgedb
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class GetUserByUsernameResult(NoPydanticValidation):
    id: uuid.UUID
    name: str
    email: str
    username: str
    admin: bool
    subscriber: bool
    hashed_password: str


async def get_user_by_username(
    executor: edgedb.AsyncIOExecutor,
    arg0: str,
) -> GetUserByUsernameResult | None:
    return await executor.query_single(
        """\
        # getUserByUsername.edgeql

        select User {
          name,
          email,
          username,
          admin,
          subscriber,
          hashed_password
        } filter .username = <str>$0\
        """,
        arg0,
    )
